# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\RSA_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RSA(object):
    def setupUi(self, RSA):
        RSA.setObjectName("RSA")
        RSA.resize(1200, 660)
        RSA.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.centralwidget = QtWidgets.QWidget(RSA)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 280, 35))
        self.label.setStyleSheet("font: 18pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(880, 20, 310, 35))
        self.label_2.setStyleSheet("font: 18pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 210, 230, 35))
        self.label_3.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(880, 210, 230, 35))
        self.label_4.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 420, 230, 35))
        self.label_5.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(880, 420, 230, 35))
        self.label_6.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_6.setObjectName("label_6")
        self.Text_pro_sifrovani = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_pro_sifrovani.setGeometry(QtCore.QRect(10, 60, 271, 151))
        self.Text_pro_sifrovani.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";")
        self.Text_pro_sifrovani.setObjectName("Text_pro_sifrovani")
        self.Text_pro_desifrovani = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_pro_desifrovani.setGeometry(QtCore.QRect(880, 60, 271, 151))
        self.Text_pro_desifrovani.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";")
        self.Text_pro_desifrovani.setObjectName("Text_pro_desifrovani")
        self.Binarni_zobrazeni_sifrovani = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Binarni_zobrazeni_sifrovani.setGeometry(QtCore.QRect(10, 250, 271, 151))
        self.Binarni_zobrazeni_sifrovani.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";")
        self.Binarni_zobrazeni_sifrovani.setObjectName("Binarni_zobrazeni_sifrovani")
        self.Binarni_zobrazeni_desifrovani = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Binarni_zobrazeni_desifrovani.setGeometry(QtCore.QRect(880, 250, 271, 151))
        self.Binarni_zobrazeni_desifrovani.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";")
        self.Binarni_zobrazeni_desifrovani.setObjectName("Binarni_zobrazeni_desifrovani")
        self.Zasifrovany_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Zasifrovany_text.setGeometry(QtCore.QRect(10, 460, 271, 151))
        self.Zasifrovany_text.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";")
        self.Zasifrovany_text.setObjectName("Zasifrovany_text")
        self.Desifrovany_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Desifrovany_text.setGeometry(QtCore.QRect(880, 460, 271, 151))
        self.Desifrovany_text.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";")
        self.Desifrovany_text.setObjectName("Desifrovany_text")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(300, 30, 560, 580))
        self.frame.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Generovat_Button = QtWidgets.QPushButton(self.frame)
        self.Generovat_Button.setGeometry(QtCore.QRect(220, 145, 120, 40))
        self.Generovat_Button.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(36, 36, 36);\n"
"font: 700 12pt \"Segoe UI\";")
        self.Generovat_Button.setObjectName("Generovat_Button")
        self.E = QtWidgets.QLineEdit(self.frame)
        self.E.setGeometry(QtCore.QRect(360, 50, 180, 30))
        self.E.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";")
        self.E.setObjectName("E")
        self.P = QtWidgets.QLineEdit(self.frame)
        self.P.setGeometry(QtCore.QRect(20, 50, 180, 30))
        self.P.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";")
        self.P.setObjectName("P")
        self.FI = QtWidgets.QLineEdit(self.frame)
        self.FI.setGeometry(QtCore.QRect(20, 150, 180, 30))
        self.FI.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";")
        self.FI.setObjectName("FI")
        self.N = QtWidgets.QLineEdit(self.frame)
        self.N.setGeometry(QtCore.QRect(360, 150, 180, 30))
        self.N.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";")
        self.N.setObjectName("N")
        self.D = QtWidgets.QLineEdit(self.frame)
        self.D.setGeometry(QtCore.QRect(360, 250, 180, 30))
        self.D.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";")
        self.D.setObjectName("D")
        self.Q = QtWidgets.QLineEdit(self.frame)
        self.Q.setGeometry(QtCore.QRect(20, 250, 180, 30))
        self.Q.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 11pt \"Segoe UI\";")
        self.Q.setObjectName("Q")
        self.tabulka = QtWidgets.QTableWidget(self.frame)
        self.tabulka.setGeometry(QtCore.QRect(20, 320, 521, 241))
        self.tabulka.setStyleSheet("font: 11pt \"Segoe UI\";")
        self.tabulka.setObjectName("tabulka")
        self.tabulka.setColumnCount(6)
        self.tabulka.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabulka.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabulka.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabulka.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabulka.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabulka.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabulka.setHorizontalHeaderItem(5, item)
        self.tabulka.horizontalHeader().setDefaultSectionSize(86)
        self.tabulka.horizontalHeader().setHighlightSections(True)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(95, 10, 30, 35))
        self.label_7.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(95, 110, 30, 35))
        self.label_8.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(95, 210, 30, 35))
        self.label_9.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(435, 210, 30, 35))
        self.label_10.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(435, 10, 30, 35))
        self.label_11.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(435, 110, 30, 35))
        self.label_12.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_12.setObjectName("label_12")
        RSA.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RSA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        RSA.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RSA)
        self.statusbar.setObjectName("statusbar")
        RSA.setStatusBar(self.statusbar)

        self.retranslateUi(RSA)
        QtCore.QMetaObject.connectSlotsByName(RSA)

    def retranslateUi(self, RSA):
        _translate = QtCore.QCoreApplication.translate
        RSA.setWindowTitle(_translate("RSA", "RSA"))
        self.label.setText(_translate("RSA", "Zadejte text pro šifrování:"))
        self.label_2.setText(_translate("RSA", "Zadejte text pro dešifrování:"))
        self.label_3.setText(_translate("RSA", "Binární zobrazení:"))
        self.label_4.setText(_translate("RSA", "Binární zobrazení:"))
        self.label_5.setText(_translate("RSA", "Zašifrovaný text:"))
        self.label_6.setText(_translate("RSA", "Dešifrovaný text:"))
        self.Generovat_Button.setText(_translate("RSA", "Generovat"))
        item = self.tabulka.horizontalHeaderItem(0)
        item.setText(_translate("RSA", "Index"))
        item = self.tabulka.horizontalHeaderItem(1)
        item.setText(_translate("RSA", "Char"))
        item = self.tabulka.horizontalHeaderItem(2)
        item.setText(_translate("RSA", "ASCII"))
        item = self.tabulka.horizontalHeaderItem(3)
        item.setText(_translate("RSA", "Binary"))
        item = self.tabulka.horizontalHeaderItem(4)
        item.setText(_translate("RSA", "Total"))
        item = self.tabulka.horizontalHeaderItem(5)
        item.setText(_translate("RSA", "Total Binary"))
        self.label_7.setText(_translate("RSA", "<html><head/><body><p align=\"center\">P</p></body></html>"))
        self.label_8.setText(_translate("RSA", "<html><head/><body><p align=\"center\">FI</p></body></html>"))
        self.label_9.setText(_translate("RSA", "<html><head/><body><p align=\"center\">Q</p></body></html>"))
        self.label_10.setText(_translate("RSA", "<html><head/><body><p align=\"center\">D</p></body></html>"))
        self.label_11.setText(_translate("RSA", "<html><head/><body><p align=\"center\">E</p></body></html>"))
        self.label_12.setText(_translate("RSA", "<html><head/><body><p align=\"center\">N</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RSA = QtWidgets.QMainWindow()
    ui = Ui_RSA()
    ui.setupUi(RSA)
    RSA.show()
    sys.exit(app.exec_())
