# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playfair_cipher.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Playfair_cipher(object):
    def setupUi(self, Playfair_cipher):
        Playfair_cipher.setObjectName("Playfair_cipher")
        Playfair_cipher.resize(800, 600)
        Playfair_cipher.setStyleSheet("background-color: rgb(84, 84, 84);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.centralwidget = QtWidgets.QWidget(Playfair_cipher)
        self.centralwidget.setObjectName("centralwidget")
        self.Zasifrovat_button = QtWidgets.QPushButton(self.centralwidget)
        self.Zasifrovat_button.setGeometry(QtCore.QRect(70, 270, 111, 51))
        self.Zasifrovat_button.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(206, 206, 206);\n"
"background-color: rgb(0, 148, 202);\n"
"color: rgb(255, 255, 255);")
        self.Zasifrovat_button.setObjectName("Zasifrovat_button")
        self.Desifrovat_button = QtWidgets.QPushButton(self.centralwidget)
        self.Desifrovat_button.setGeometry(QtCore.QRect(620, 270, 111, 51))
        self.Desifrovat_button.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(206, 206, 206);\n"
"background-color: rgb(0, 148, 202);\n"
"color: rgb(255, 255, 255);")
        self.Desifrovat_button.setObjectName("Desifrovat_button")
        self.Mezivysledky = QtWidgets.QPushButton(self.centralwidget)
        self.Mezivysledky.setGeometry(QtCore.QRect(330, 260, 131, 51))
        self.Mezivysledky.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(206, 206, 206);\n"
"background-color: rgb(0, 148, 202);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.Mezivysledky.setObjectName("Mezivysledky")
        self.Zobrazeni_tabulky = QtWidgets.QPushButton(self.centralwidget)
        self.Zobrazeni_tabulky.setGeometry(QtCore.QRect(330, 500, 131, 51))
        self.Zobrazeni_tabulky.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(206, 206, 206);\n"
"background-color: rgb(0, 148, 202);\n"
"color: rgb(255, 255, 255);")
        self.Zobrazeni_tabulky.setObjectName("Zobrazeni_tabulky")
        self.Nadpis_zasifrovat = QtWidgets.QLabel(self.centralwidget)
        self.Nadpis_zasifrovat.setGeometry(QtCore.QRect(30, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Nadpis_zasifrovat.setFont(font)
        self.Nadpis_zasifrovat.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(73, 255, 79);")
        self.Nadpis_zasifrovat.setObjectName("Nadpis_zasifrovat")
        self.Nadpis_desifrovat = QtWidgets.QLabel(self.centralwidget)
        self.Nadpis_desifrovat.setGeometry(QtCore.QRect(580, 60, 191, 41))
        self.Nadpis_desifrovat.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(73, 255, 79);")
        self.Nadpis_desifrovat.setObjectName("Nadpis_desifrovat")
        self.Nadpis_vlozit_text_sifrovani = QtWidgets.QLabel(self.centralwidget)
        self.Nadpis_vlozit_text_sifrovani.setGeometry(QtCore.QRect(30, 100, 201, 31))
        self.Nadpis_vlozit_text_sifrovani.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.Nadpis_vlozit_text_sifrovani.setObjectName("Nadpis_vlozit_text_sifrovani")
        self.Nadpis_vlozit_text_desifrovani = QtWidgets.QLabel(self.centralwidget)
        self.Nadpis_vlozit_text_desifrovani.setGeometry(QtCore.QRect(580, 100, 211, 21))
        self.Nadpis_vlozit_text_desifrovani.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.Nadpis_vlozit_text_desifrovani.setObjectName("Nadpis_vlozit_text_desifrovani")
        self.Vlozt_klic_sifrovani = QtWidgets.QLabel(self.centralwidget)
        self.Vlozt_klic_sifrovani.setGeometry(QtCore.QRect(30, 230, 51, 31))
        self.Vlozt_klic_sifrovani.setObjectName("Vlozt_klic_sifrovani")
        self.Vlozit_klic_desifrovani = QtWidgets.QLabel(self.centralwidget)
        self.Vlozit_klic_desifrovani.setGeometry(QtCore.QRect(580, 230, 51, 31))
        self.Vlozit_klic_desifrovani.setObjectName("Vlozit_klic_desifrovani")
        self.Sifrovany_text = QtWidgets.QLabel(self.centralwidget)
        self.Sifrovany_text.setGeometry(QtCore.QRect(30, 340, 191, 31))
        self.Sifrovany_text.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.Sifrovany_text.setObjectName("Sifrovany_text")
        self.Desifrovany_text = QtWidgets.QLabel(self.centralwidget)
        self.Desifrovany_text.setGeometry(QtCore.QRect(580, 340, 191, 31))
        self.Desifrovany_text.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.Desifrovany_text.setObjectName("Desifrovany_text")
        self.Klic_k_sifrovani = QtWidgets.QLineEdit(self.centralwidget)
        self.Klic_k_sifrovani.setGeometry(QtCore.QRect(80, 230, 141, 31))
        self.Klic_k_sifrovani.setObjectName("Klic_k_sifrovani")
        self.Klic_k_desifrovani = QtWidgets.QLineEdit(self.centralwidget)
        self.Klic_k_desifrovani.setGeometry(QtCore.QRect(630, 230, 141, 31))
        self.Klic_k_desifrovani.setObjectName("Klic_k_desifrovani")
        self.Nadpis = QtWidgets.QLabel(self.centralwidget)
        self.Nadpis.setGeometry(QtCore.QRect(30, 0, 221, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Nadpis.setFont(font)
        self.Nadpis.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.Nadpis.setObjectName("Nadpis")
        self.Text_pro_sifrovani = QtWidgets.QTextEdit(self.centralwidget)
        self.Text_pro_sifrovani.setGeometry(QtCore.QRect(30, 130, 191, 91))
        self.Text_pro_sifrovani.setObjectName("Text_pro_sifrovani")
        self.Text_pro_desifrovani = QtWidgets.QTextEdit(self.centralwidget)
        self.Text_pro_desifrovani.setGeometry(QtCore.QRect(580, 130, 191, 91))
        self.Text_pro_desifrovani.setObjectName("Text_pro_desifrovani")
        self.Zasifrovany_text = QtWidgets.QTextEdit(self.centralwidget)
        self.Zasifrovany_text.setGeometry(QtCore.QRect(30, 380, 191, 91))
        self.Zasifrovany_text.setObjectName("Zasifrovany_text")
        self.Desifrovany_text_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.Desifrovany_text_3.setGeometry(QtCore.QRect(580, 380, 191, 91))
        self.Desifrovany_text_3.setObjectName("Desifrovany_text_3")
        self.matice_vypis = QtWidgets.QTextEdit(self.centralwidget)
        self.matice_vypis.setGeometry(QtCore.QRect(310, 330, 171, 161))
        self.matice_vypis.setObjectName("matice_vypis")
        self.mezivysledky_vypis = QtWidgets.QTextEdit(self.centralwidget)
        self.mezivysledky_vypis.setGeometry(QtCore.QRect(290, 0, 211, 241))
        self.mezivysledky_vypis.setObjectName("mezivysledky_vypis")
        self.key_size = QtWidgets.QLineEdit(self.centralwidget)
        self.key_size.setGeometry(QtCore.QRect(580, 10, 191, 31))
        self.key_size.setObjectName("key_size")
        Playfair_cipher.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Playfair_cipher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuPlayfairova_ifra = QtWidgets.QMenu(self.menubar)
        self.menuPlayfairova_ifra.setObjectName("menuPlayfairova_ifra")
        Playfair_cipher.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Playfair_cipher)
        self.statusbar.setObjectName("statusbar")
        Playfair_cipher.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPlayfairova_ifra.menuAction())

        self.retranslateUi(Playfair_cipher)
        QtCore.QMetaObject.connectSlotsByName(Playfair_cipher)

    def retranslateUi(self, Playfair_cipher):
        _translate = QtCore.QCoreApplication.translate
        Playfair_cipher.setWindowTitle(_translate("Playfair_cipher", "MainWindow"))
        self.Zasifrovat_button.setText(_translate("Playfair_cipher", "Zašifrovat"))
        self.Desifrovat_button.setText(_translate("Playfair_cipher", "Dešifrovat"))
        self.Mezivysledky.setText(_translate("Playfair_cipher", "Mezivýsledky"))
        self.Zobrazeni_tabulky.setText(_translate("Playfair_cipher", "Zobrazit tabulku"))
        self.Nadpis_zasifrovat.setText(_translate("Playfair_cipher", "Zašifrovat"))
        self.Nadpis_desifrovat.setText(_translate("Playfair_cipher", "Dešifrovat"))
        self.Nadpis_vlozit_text_sifrovani.setText(_translate("Playfair_cipher", "Vložte text pro zašifrování:"))
        self.Nadpis_vlozit_text_desifrovani.setText(_translate("Playfair_cipher", "Vložte text pro dešifrování: "))
        self.Vlozt_klic_sifrovani.setText(_translate("Playfair_cipher", "Klíč:"))
        self.Vlozit_klic_desifrovani.setText(_translate("Playfair_cipher", "Klíč: "))
        self.Sifrovany_text.setText(_translate("Playfair_cipher", "Zašifrovaný text:"))
        self.Desifrovany_text.setText(_translate("Playfair_cipher", "Dešifrovaný text: "))
        self.Nadpis.setText(_translate("Playfair_cipher", "Playfairova šifra"))
        self.menuPlayfairova_ifra.setTitle(_translate("Playfair_cipher", "Playfair Cipher"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Playfair_cipher = QtWidgets.QMainWindow()
    ui = Ui_Playfair_cipher()
    ui.setupUi(Playfair_cipher)
    Playfair_cipher.show()
    sys.exit(app.exec_())
