# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Afinni_Sifra.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AfinniSifra(object):
    def setupUi(self, AfinniSifra):
        AfinniSifra.setObjectName("AfinniSifra")
        AfinniSifra.resize(300, 600)
        AfinniSifra.setStyleSheet("background-color: rgb(76, 76, 76);")
        self.centralwidget = QtWidgets.QWidget(AfinniSifra)
        self.centralwidget.setObjectName("centralwidget")
        self.ZakodovatButton = QtWidgets.QPushButton(self.centralwidget)
        self.ZakodovatButton.setGeometry(QtCore.QRect(100, 150, 100, 30))
        self.ZakodovatButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(138, 138, 138);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.ZakodovatButton.setObjectName("ZakodovatButton")
        self.DekodovatButton = QtWidgets.QPushButton(self.centralwidget)
        self.DekodovatButton.setGeometry(QtCore.QRect(100, 390, 100, 30))
        self.DekodovatButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(138, 138, 138);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.DekodovatButton.setObjectName("DekodovatButton")
        self.Text_Zakodovani = QtWidgets.QLabel(self.centralwidget)
        self.Text_Zakodovani.setGeometry(QtCore.QRect(50, 40, 200, 40))
        self.Text_Zakodovani.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(12, 243, 0);")
        self.Text_Zakodovani.setObjectName("Text_Zakodovani")
        self.Text_Dekodovani = QtWidgets.QLabel(self.centralwidget)
        self.Text_Dekodovani.setGeometry(QtCore.QRect(50, 280, 200, 40))
        self.Text_Dekodovani.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
"color: rgb(12, 243, 0);")
        self.Text_Dekodovani.setObjectName("Text_Dekodovani")
        self.Vstup_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.Vstup_1.setGeometry(QtCore.QRect(48, 90, 200, 50))
        self.Vstup_1.setStyleSheet("color: rgb(239, 239, 239);")
        self.Vstup_1.setObjectName("Vstup_1")
        self.Vstup_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.Vstup_2.setGeometry(QtCore.QRect(48, 330, 200, 50))
        self.Vstup_2.setStyleSheet("color: rgb(239, 239, 239);")
        self.Vstup_2.setObjectName("Vstup_2")
        self.Vystup_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.Vystup_1.setGeometry(QtCore.QRect(48, 230, 200, 50))
        self.Vystup_1.setStyleSheet("color: rgb(239, 239, 239);")
        self.Vystup_1.setObjectName("Vystup_1")
        self.Vystup_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.Vystup_2.setGeometry(QtCore.QRect(48, 470, 200, 50))
        self.Vystup_2.setStyleSheet("color: rgb(239, 239, 239);")
        self.Vystup_2.setObjectName("Vystup_2")
        self.ZakodovanyText = QtWidgets.QLabel(self.centralwidget)
        self.ZakodovanyText.setGeometry(QtCore.QRect(80, 180, 140, 40))
        self.ZakodovanyText.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(12, 243, 0);")
        self.ZakodovanyText.setObjectName("ZakodovanyText")
        self.DekodovanyText = QtWidgets.QLabel(self.centralwidget)
        self.DekodovanyText.setGeometry(QtCore.QRect(80, 420, 140, 40))
        self.DekodovanyText.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(12, 243, 0);")
        self.DekodovanyText.setObjectName("DekodovanyText")
        self.klic_a = QtWidgets.QLineEdit(self.centralwidget)
        self.klic_a.setGeometry(QtCore.QRect(80, 10, 51, 22))
        self.klic_a.setStyleSheet("color: rgb(239, 239, 239);")
        self.klic_a.setObjectName("klic_a")
        self.klic_b = QtWidgets.QLineEdit(self.centralwidget)
        self.klic_b.setGeometry(QtCore.QRect(180, 10, 51, 22))
        self.klic_b.setStyleSheet("color: rgb(239, 239, 239);")
        self.klic_b.setObjectName("klic_b")
        self.hodnota_a = QtWidgets.QLabel(self.centralwidget)
        self.hodnota_a.setGeometry(QtCore.QRect(60, 10, 21, 21))
        self.hodnota_a.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 0);")
        self.hodnota_a.setObjectName("hodnota_a")
        self.hodnota_b = QtWidgets.QLabel(self.centralwidget)
        self.hodnota_b.setGeometry(QtCore.QRect(160, 10, 21, 21))
        self.hodnota_b.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 0);")
        self.hodnota_b.setObjectName("hodnota_b")
        AfinniSifra.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AfinniSifra)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        AfinniSifra.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AfinniSifra)
        self.statusbar.setObjectName("statusbar")
        AfinniSifra.setStatusBar(self.statusbar)

        self.retranslateUi(AfinniSifra)
        QtCore.QMetaObject.connectSlotsByName(AfinniSifra)

    def retranslateUi(self, AfinniSifra):
        _translate = QtCore.QCoreApplication.translate
        AfinniSifra.setWindowTitle(_translate("AfinniSifra", "MainWindow"))
        self.ZakodovatButton.setText(_translate("AfinniSifra", "Zakódovat"))
        self.DekodovatButton.setText(_translate("AfinniSifra", "Dekódovat"))
        self.Text_Zakodovani.setText(_translate("AfinniSifra", "Text pro zakódování"))
        self.Text_Dekodovani.setText(_translate("AfinniSifra", "Text pro dekódování"))
        self.ZakodovanyText.setText(_translate("AfinniSifra", "Zakódovaný text"))
        self.DekodovanyText.setText(_translate("AfinniSifra", "Dekódovaný text"))
        self.hodnota_a.setText(_translate("AfinniSifra", "a:"))
        self.hodnota_b.setText(_translate("AfinniSifra", "b:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AfinniSifra = QtWidgets.QMainWindow()
    ui = Ui_AfinniSifra()
    ui.setupUi(AfinniSifra)
    AfinniSifra.show()
    sys.exit(app.exec_())
