# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DSA_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DSA(object):
    def setupUi(self, DSA):
        DSA.setObjectName("DSA")
        DSA.resize(700, 650)
        DSA.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.centralwidget = QtWidgets.QWidget(DSA)
        self.centralwidget.setObjectName("centralwidget")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(30, 350, 110, 35))
        self.label_11.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(370, 350, 130, 35))
        self.label_12.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(100, 10, 211, 35))
        self.label_13.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(430, 10, 170, 35))
        self.label_14.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(30, 50, 131, 35))
        self.label_15.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(30, 100, 131, 35))
        self.label_16.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(30, 150, 131, 35))
        self.label_17.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(30, 200, 131, 35))
        self.label_18.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_18.setObjectName("label_18")
        self.nacist_soubor_button = QtWidgets.QPushButton(self.centralwidget)
        self.nacist_soubor_button.setGeometry(QtCore.QRect(30, 300, 130, 40))
        self.nacist_soubor_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.nacist_soubor_button.setObjectName("nacist_soubor_button")
        self.podepsat_soubor_button = QtWidgets.QPushButton(self.centralwidget)
        self.podepsat_soubor_button.setGeometry(QtCore.QRect(180, 300, 130, 40))
        self.podepsat_soubor_button.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.podepsat_soubor_button.setObjectName("podepsat_soubor_button")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(340, 50, 151, 35))
        self.label_19.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(340, 100, 151, 35))
        self.label_20.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_20.setObjectName("label_20")
        self.nacist_zip = QtWidgets.QPushButton(self.centralwidget)
        self.nacist_zip.setGeometry(QtCore.QRect(370, 300, 130, 40))
        self.nacist_zip.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.nacist_zip.setObjectName("nacist_zip")
        self.overit = QtWidgets.QPushButton(self.centralwidget)
        self.overit.setGeometry(QtCore.QRect(520, 300, 130, 40))
        self.overit.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.overit.setObjectName("overit")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(30, 245, 51, 35))
        self.label_21.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_21.setObjectName("label_21")
        self.nazev_souboru = QtWidgets.QLineEdit(self.centralwidget)
        self.nazev_souboru.setGeometry(QtCore.QRect(169, 55, 160, 35))
        self.nazev_souboru.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Segoe UI\";")
        self.nazev_souboru.setObjectName("nazev_souboru")
        self.cesta_k_souboru = QtWidgets.QLineEdit(self.centralwidget)
        self.cesta_k_souboru.setGeometry(QtCore.QRect(170, 105, 160, 35))
        self.cesta_k_souboru.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Segoe UI\";")
        self.cesta_k_souboru.setObjectName("cesta_k_souboru")
        self.velikost_souboru = QtWidgets.QLineEdit(self.centralwidget)
        self.velikost_souboru.setGeometry(QtCore.QRect(170, 155, 160, 35))
        self.velikost_souboru.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Segoe UI\";")
        self.velikost_souboru.setObjectName("velikost_souboru")
        self.datum_vytvoreni = QtWidgets.QLineEdit(self.centralwidget)
        self.datum_vytvoreni.setGeometry(QtCore.QRect(170, 205, 160, 35))
        self.datum_vytvoreni.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Segoe UI\";")
        self.datum_vytvoreni.setObjectName("datum_vytvoreni")
        self.stav_zip_souboru = QtWidgets.QLineEdit(self.centralwidget)
        self.stav_zip_souboru.setGeometry(QtCore.QRect(500, 55, 160, 35))
        self.stav_zip_souboru.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Segoe UI\";")
        self.stav_zip_souboru.setObjectName("stav_zip_souboru")
        self.cesta_k_zip_souboru = QtWidgets.QLineEdit(self.centralwidget)
        self.cesta_k_zip_souboru.setGeometry(QtCore.QRect(500, 105, 160, 35))
        self.cesta_k_zip_souboru.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Segoe UI\";")
        self.cesta_k_zip_souboru.setObjectName("cesta_k_zip_souboru")
        self.stav_je = QtWidgets.QLineEdit(self.centralwidget)
        self.stav_je.setGeometry(QtCore.QRect(90, 250, 561, 35))
        self.stav_je.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Segoe UI\";")
        self.stav_je.setObjectName("stav_je")
        self.verejny_klic = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.verejny_klic.setGeometry(QtCore.QRect(30, 390, 281, 141))
        self.verejny_klic.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Segoe UI\";")
        self.verejny_klic.setObjectName("verejny_klic")
        self.soukromy_klic = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.soukromy_klic.setGeometry(QtCore.QRect(370, 390, 281, 141))
        self.soukromy_klic.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"Segoe UI\";")
        self.soukromy_klic.setObjectName("soukromy_klic")
        self.generovat_klice = QtWidgets.QPushButton(self.centralwidget)
        self.generovat_klice.setGeometry(QtCore.QRect(30, 550, 281, 40))
        self.generovat_klice.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.generovat_klice.setObjectName("generovat_klice")
        self.nacist_klice = QtWidgets.QPushButton(self.centralwidget)
        self.nacist_klice.setGeometry(QtCore.QRect(370, 550, 281, 40))
        self.nacist_klice.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Segoe UI\";")
        self.nacist_klice.setObjectName("nacist_klice")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(340, 150, 151, 35))
        self.label_22.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"color: rgb(242, 255, 0);")
        self.label_22.setObjectName("label_22")
        self.nazev_zipu = QtWidgets.QLineEdit(self.centralwidget)
        self.nazev_zipu.setGeometry(QtCore.QRect(500, 155, 160, 35))
        self.nazev_zipu.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Segoe UI\";")
        self.nazev_zipu.setObjectName("nazev_zipu")
        DSA.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DSA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        DSA.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DSA)
        self.statusbar.setObjectName("statusbar")
        DSA.setStatusBar(self.statusbar)

        self.retranslateUi(DSA)
        QtCore.QMetaObject.connectSlotsByName(DSA)

    def retranslateUi(self, DSA):
        _translate = QtCore.QCoreApplication.translate
        DSA.setWindowTitle(_translate("DSA", "MainWindow"))
        self.label_11.setText(_translate("DSA", "<html><head/><body><p>Veřejný klíč</p></body></html>"))
        self.label_12.setText(_translate("DSA", "<html><head/><body><p>Soukromý klíč</p><p><br/></p></body></html>"))
        self.label_13.setText(_translate("DSA", "<html><head/><body><p><span style=\" font-size:16pt;\">Informace o souboru</span></p></body></html>"))
        self.label_14.setText(_translate("DSA", "<html><head/><body><p><span style=\" font-size:16pt;\">Ověření souboru</span></p></body></html>"))
        self.label_15.setText(_translate("DSA", "<html><head/><body><p><span style=\" font-size:12pt;\">Název souboru:</span></p></body></html>"))
        self.label_16.setText(_translate("DSA", "<html><head/><body><p><span style=\" font-size:12pt;\">Cesta k souboru:</span></p></body></html>"))
        self.label_17.setText(_translate("DSA", "<html><head/><body><p><span style=\" font-size:12pt;\">Velikost souboru:</span></p></body></html>"))
        self.label_18.setText(_translate("DSA", "<html><head/><body><p><span style=\" font-size:12pt;\">Datum vytvoření:</span></p></body></html>"))
        self.nacist_soubor_button.setText(_translate("DSA", "Načíst soubor"))
        self.podepsat_soubor_button.setText(_translate("DSA", "Podepsat soubor"))
        self.label_19.setText(_translate("DSA", "<html><head/><body><p><span style=\" font-size:12pt;\">ZIP soubor:</span></p></body></html>"))
        self.label_20.setText(_translate("DSA", "<html><head/><body><p><span style=\" font-size:12pt;\">Cesta k ZIP souboru:</span></p></body></html>"))
        self.nacist_zip.setText(_translate("DSA", "Načíst ZIP"))
        self.overit.setText(_translate("DSA", "Ověřit"))
        self.label_21.setText(_translate("DSA", "<html><head/><body><p><span style=\" font-size:12pt;\">Stav:</span></p></body></html>"))
        self.generovat_klice.setText(_translate("DSA", "Generovat klíče"))
        self.nacist_klice.setText(_translate("DSA", "Načíst klíče"))
        self.label_22.setText(_translate("DSA", "<html><head/><body><p><span style=\" font-size:12pt;\">Název souboru:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DSA = QtWidgets.QMainWindow()
    ui = Ui_DSA()
    ui.setupUi(DSA)
    DSA.show()
    sys.exit(app.exec_())
